# Generated by Django 5.0.7 on 2024-11-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tution', '0004_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='media/images'),
        ),
    ]
